services:
  mysql:
    image: mysql:latest
    container_name: chattingo_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: chattingo_db
    ports:
      - "3306:3306"
    networks:
      - chattingo-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  backend:
    build:
      context: ./backend
    container_name: chattingo-backend
    env_file:
      - ./backend/.env
    ports:
      - "8081:8080"
    networks:
      - chattingo-network
    depends_on:
      - mysql
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s


  frontend:
    build:
      context: ./frontend
    container_name: chattingo-frontend
    ports:
      - "3000:80"
    networks:
      - chattingo-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  chattingo-network:
